# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = GenshinImpact_AutoMap
DESTDIR = ../x64/Debug
CONFIG += debug
CONFIG += resources_big
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(GenshinImpact_AutoMap.pri)
